### PR TITLE
Upgrade toran proxy to version 1.2.0

### PR DESCRIPTION
**Pull request by cedvan**
- Upgrade toran proxy to version 1.2.0
- Global clean
- Rename environment variable `TORAN_PHP_TIMEZONE` to `PHP_TIMEZONE`
- Change user nginx and php-fpm from `root` to `www-data`
- Upgrade image base to `cedvan/ubuntu:14.04.20160326`

### CODE REVIEW

**Comment by adamlc** [comment]
Can this be merged? :+1:

**Comment by cedvan** [comment]
@adamlc, I have one last test, I merge this PR this weekend :wink:

**Comment by dfeyer** [comment]
Any news for the PR ? Or any plan to upgrade to toran 1.3 directly ? Thanks

Edit: sorry i don't ready https://github.com/cedvan/docker-toran-proxy/issues/20 first ... shame on me

**Comment by cedvan** [comment]
v1.2.0 is published !

@dfeyer, pull request for upgrade to v1.3.2 #26

**Pull request merged**
