### PR TITLE
Update toran-proxy to v1.3.2

### PR DESCRIPTION
**Pull request by cedvan**
v1.3.0 and v1.3.1 have bugs, so update directly to v1.3.2

### CODE REVIEW

**Comment by salamachinas** [comment]
How is going with update to 1.3.2 ?

**Comment by cedvan** [comment]
@salamachinas I need to test all features

**Comment by salamachinas** [comment]
@cedvan how much +/- time it takes ?

**Comment by cedvan** [comment]
@salamachinas I'll try to do it tonight

**Comment by cedvan** [comment]
Waiting https://github.com/cedvan/docker-toran-proxy/issues/27 to progress

**Pull request merged**
