### PR TITLE
Upgrade toran proxy to version 1.4.4

### PR DESCRIPTION
**Pull request by cedvan**

### CODE REVIEW

**Comment by oligriffiths** [comment]
Bump, see https://github.com/cedvan/docker-toran-proxy/issues/35

**Comment by jeremyzahner** [comment]
@cedvan I'd be willing to take over updating the repo on a regular schedule, if you could give me merge access. Right now we should make sure that updates get merged on a regular base.

**Comment by cedvan** [comment]
@jeremyzahner I'm sorry, I had some problems in my private life now. I resumed the regular updating very quickly :wink:. Thank you for your proposal

**Comment by adamlc** [comment]
@cedvan can @jeremyzahner take over? Unfortunately we're going to have to start to look for alternative images if this doesn't stay updated :(

**Comment by cedvan** [comment]
Hi @adamlc,

I am in holiday tomorrow, I will update this image :wink:

**Comment by cedvan** [comment]
Pull request is outdated : https://github.com/cedvan/docker-toran-proxy/releases/tag/1.4.4

**Comment by cedvan** [comment]
Thank you for contributing

**Pull request closed without merging**
